modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="godgun"
version="1.0.0"
displayName="God Gun"
description="Point. Hold. Obliterate."

[[dependencies.godgun]]
    modId="forge"
    mandatory=true
    versionRange="[47.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.godgun]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
